# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{duke}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Justin Marney"]
  s.date = %q{2010-11-08}
  s.default_executable = %q{duke}
  s.description = %q{Allows you to easily manage multiple CIJoes.}
  s.email = %q{gotascii@gmail.com}
  s.executables = ["duke"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "Gemfile",
     "Gemfile.lock",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/duke",
     "duke.gemspec",
     "lib/duke.rb",
     "lib/duke/app.rb",
     "lib/duke/cli.rb",
     "lib/duke/controller.rb",
     "lib/duke/project.rb",
     "lib/ext/string.rb",
     "spec/duke/cli_spec.rb",
     "spec/duke/controller_spec.rb",
     "spec/duke/project_spec.rb",
     "spec/spec_helper.rb",
     "templates/config.ru",
     "templates/public/help.html",
     "templates/public/stylesheets/base.css",
     "templates/public/stylesheets/button.css",
     "templates/public/stylesheets/custom.css",
     "templates/public/stylesheets/reset.css",
     "templates/views/index.rhtml"
  ]
  s.homepage = %q{http://github.com/gotascii/duke}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Manage your CIJoes.}
  s.test_files = [
    "spec/duke/cli_spec.rb",
     "spec/duke/controller_spec.rb",
     "spec/duke/project_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<thor>, [">= 0"])
      s.add_runtime_dependency(%q<cijoe>, [">= 0"])
      s.add_runtime_dependency(%q<daemon_controller>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 2.0.1"])
    else
      s.add_dependency(%q<thor>, [">= 0"])
      s.add_dependency(%q<cijoe>, [">= 0"])
      s.add_dependency(%q<daemon_controller>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 2.0.1"])
    end
  else
    s.add_dependency(%q<thor>, [">= 0"])
    s.add_dependency(%q<cijoe>, [">= 0"])
    s.add_dependency(%q<daemon_controller>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 2.0.1"])
  end
end

